services:
  client:
    container_name: "emarket-client"
    build:
      context: "./client/"
      dockerfile: "Dockerfile"
      target: "development"
    ports:
      - "3000:3000"
    volumes:
      - "./client/:/usr/src/app/"
      - "/usr/src/app/node_modules"
    restart: unless-stopped

  server:
    container_name: "emarket-server"
    build:
      context: "./server/"
      dockerfile: "Dockerfile"
      target: "development"
    ports:
      - "3001:3001"
    volumes:
      - "./server/:/usr/src/app/"
      - "/usr/src/app/node_modules"
    restart: unless-stopped
